# Generated by Django 3.2.8 on 2021-10-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='available',
            new_name='active',
        ),
    ]
